### ISSUE TITLE
Randomly stops sending log to PaperTrail endpoint

### ISSUE THREAD

**Issue by tatobi** [solarwinds/fluent-plugin-papertrail#25]
I can't figure out from the error message we get randomly, what is the real problem, but the plugin stops sending logs:

```
2018-10-17 12:55:14 +0000 [warn]: failed to flush the buffer. retry_time=0 next_retry_seconds=2018-10-17 12:55:15 +0000 chunk="5786c2e64b0dca0038a4b247899ff483" error_class=ArgumentError error="'I' is not a designated severity"
  2018-10-17 12:55:14 +0000 [warn]: /var/lib/gems/2.3.0/gems/syslog_protocol-0.9.2/lib/syslog_protocol/packet.rb:72:in `severity='
  2018-10-17 12:55:14 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-papertrail-0.2.6/lib/fluent/plugin/out_papertrail.rb:82:in `create_packet'
  2018-10-17 12:55:14 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-papertrail-0.2.6/lib/fluent/plugin/out_papertrail.rb:44:in `block in write'
  2018-10-17 12:55:14 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/event.rb:323:in `each'
  2018-10-17 12:55:14 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/event.rb:323:in `block in each'
  2018-10-17 12:55:14 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/plugin/buffer/memory_chunk.rb:80:in `open'
  2018-10-17 12:55:14 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/plugin/buffer/memory_chunk.rb:80:in `open'
  2018-10-17 12:55:14 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/event.rb:322:in `each'
  2018-10-17 12:55:14 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-papertrail-0.2.6/lib/fluent/plugin/out_papertrail.rb:39:in `write'
  2018-10-17 12:55:14 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/compat/output.rb:131:in `write'
  2018-10-17 12:55:14 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/plugin/output.rb:1094:in `try_flush'
  2018-10-17 12:55:14 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/plugin/output.rb:1319:in `flush_thread_run'
  2018-10-17 12:55:14 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/plugin/output.rb:439:in `block (2 levels) in start'
  2018-10-17 12:55:14 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2018-10-17 12:55:15 +0000 [warn]: failed to flush the buffer. retry_time=0 next_retry_seconds=2018-10-17 12:55:15 +0000 chunk="5786c2e64b0dca0038a4b247899ff483" error_class=ArgumentError error="'I' is not a designated severity"
  2018-10-17 12:55:15 +0000 [warn]: suppressed same stacktrace
2018-10-17 12:55:16 +0000 [warn]: failed to flush the buffer. retry_time=1 next_retry_seconds=2018-10-17 12:55:16 +0000 chunk="5786c2e64b0dca0038a4b247899ff483" error_class=ArgumentError error="'I' is not a designated severity"
  2018-10-17 12:55:16 +0000 [warn]: suppressed same stacktrace
2018-10-17 12:55:18 +0000 [warn]: failed to flush the buffer. retry_time=2 next_retry_seconds=2018-10-17 12:55:18 +0000 chunk="5786c2e64b0dca0038a4b247899ff483" error_class=ArgumentError error="'I' is not a designated severity"
  2018-10-17 12:55:18 +0000 [warn]: suppressed same stacktrace
2018-10-17 12:55:22 +0000 [warn]: failed to flush the buffer. retry_time=3 next_retry_seconds=2018-10-17 12:55:22 +0000 chunk="5786c2e64b0dca0038a4b247899ff483" error_class=ArgumentError error="'I' is not a designated severity"
  2018-10-17 12:55:22 +0000 [warn]: suppressed same stacktrace
2018-10-17 12:55:29 +0000 [warn]: failed to flush the buffer. retry_time=4 next_retry_seconds=2018-10-17 12:55:29 +0000 chunk="5786c2e64b0dca0038a4b247899ff483" error_class=ArgumentError error="'I' is not a designated severity"```

**Comment by cmrust** [comment]
Hey @tatobi,

The actual error message is `error="'I' is not a designated severity"`. The rest of the logs are about fluentd retrying the record and incrementally backing off, probably until it fails altogether as you've noted.

This is an error from the syslog_protocol gem we use in the plugin. You're setting severity to `I` somewhere and it's rejecting it as non-conforming. See the following links for how it handles severity and the list of accepted values: 
https://github.com/eric/syslog_protocol/blob/001000ffe27a4557c3ec312b9c3c50385e6a923b/lib/syslog_protocol/packet.rb#L61-L77
https://github.com/eric/syslog_protocol/blob/001000ffe27a4557c3ec312b9c3c50385e6a923b/lib/syslog_protocol/common.rb#L58-L78

Our plugin grabs severity from your fluent record or else defaults to 'info'. It seems you are passing the value `I` in to the severity field in fluent somewhere. You need to figure out where that is and change it.

See here for our plugin's implementation:
https://github.com/solarwinds/fluent-plugin-papertrail/blob/master/lib/fluent/plugin/out_papertrail.rb#L82

Let me know if that doesn't make sense.

**Comment by tatobi** [comment]
Hi @cmrust ,
Thank you for the quick response.

I use the config from here : https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/fluentd-es-configmap.yaml 
with replace of output.conf section with PapertTrail one:
```
....
  output.conf: |-
    # Enriches records with Kubernetes metadata
    <filter kubernetes.**>
      @type kubernetes_metadata
    </filter>
    <filter kubernetes.**>
      @type record_transformer
      enable_ruby true
      <record>
        hostname kubernetes-test-${record["kubernetes"]["pod_name"]}
        program ${record["kubernetes"]["container_name"]}
        severity info
        facility local0
        message ${record['log']}
      </record>
    </filter>
    <match **>
      @type copy
      <store>
        @type papertrail
        papertrail_host logs****.papertrailapp.com
        papertrail_port *****
      </store>
    </match>
```
I do not set `severity` anywher and it is always info as you can see.
Thats it, so it is strange.

**Comment by cmrust** [comment]
In the snippet here you are transforming all records with the prefix `kubernetes.` and forcing `severity` to `info`.

This is good, but your match to output to papertrail is for all records `**`, not just ones with that prefix.

In the link you've pasted above you have many fluent sources, many of which format severity. One of these has a bad input.

I would suggest two approaches to solve your problem:
- Set an output plugin like STDOUT instead of Papertrail and watch the output of the process until you find what is logging with severity `I` and then go fix it.
- Create another filter with record_transformer to match all events `**` and overwrite all records to have a severity of info.

Let me know how it goes @tatobi and thanks for using the plugin.

**Comment by tatobi** [comment]
Hi @cmrust ,

Thank you.

I figured out that the "I" is the common severity indetifier in Kubernetes ecosystem log messages, like in:
`/var/log/kube-proxy.log`

Line:
`# I1118 21:26:53.975789       6 proxier.go:1096] Port "nodePort for kube-system/default-http-backend:http" (:31429/tcp) was open before and is still needed`

The FD source formatter line is:
`format1 /^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source>[^ \]]+)\] (?<message>.*)/`

So it should be `info` instead in PapertTrail output, not just "I".

In my opinion this character causes the problem. Thus I consider your second option to transform and force    every event with `info` severity to PT.
Thanks again.

**Comment by tatobi** [comment]
The new output section looks like now, I hope it does what we want.
```
  output.conf: |-
    # Enriches records with Kubernetes metadata
    <filter kubernetes.**>
      @type kubernetes_metadata
    </filter>

    <filter kubernetes.**>
      @type record_transformer
      enable_ruby true
      <record>
        hostname kube-live-${record["kubernetes"]["container_name"]}
        program ${record["kubernetes"]["container_name"]}
        severity info
        facility local0
        message ${record['log']}
      </record>
    </filter>
    
    <match **>
      @type record_reformer
      enable_ruby true
      <record>
        facility local0
        message ${record['log']}
        severity info
      </record>
      
      @type copy
      <store>
        @type papertrail
        papertrail_host logs7.papertrailapp.com
        papertrail_port 10905
        flush_interval 60
        retry_limit 100
        retry_wait 10
      </store>
    </match>
```

**Comment by tatobi** [comment]
Or a second try:
```
  output.conf: |-
    # Enriches records with Kubernetes metadata
    <filter kubernetes.**>
      @type kubernetes_metadata
    </filter>

    <filter kubernetes.**>
      @type record_transformer
      enable_ruby true
      <record>
        hostname kube-live-${record["kubernetes"]["container_name"]}
        program ${record["kubernetes"]["container_name"]}
        severity info
        facility local0
        message ${record['log']}
      </record>
    </filter>

    <filter **>
      @type record_transformer
      enable_ruby true
      <record>
        facility local0
        message ${record['log']}
        severity info
      </record>
    </filter>
    
    <match **>
      @type copy
      <store>
        @type papertrail
        papertrail_host logs7.papertrailapp.com
        papertrail_port 10905
        flush_interval 60
        retry_limit 100
        retry_wait 10
      </store>
    </match>
```

**Comment by cmrust** [comment]
In retrospect, we could add an option to the plugin to override values like severity if they're not from the accepted lists.

**Comment by tatobi** [comment]
Thank you! Btw, after the second modification you mentioned, it looks like working well.

**Comment by cmrust** [comment]
Cheers. Glad to be of service @tatobi. Thanks for creating an issue and please don't hesitate to do so again.
